DROP TABLE IF EXISTS
	`ie9ab_digicom_cart`,
	`ie9ab_digicom_currencies`,
	`ie9ab_digicom_customers`,
	`ie9ab_digicom_orders`,
	`ie9ab_digicom_orders_details`,
	`ie9ab_digicom_products`,
	`ie9ab_digicom_products_bundle`,
	`ie9ab_digicom_products_files`,
	`ie9ab_digicom_products_rating`,
	`ie9ab_digicom_promocodes`,
	`ie9ab_digicom_promocodes_orders`,
	`ie9ab_digicom_promocodes_products`,
	`ie9ab_digicom_sendmails`,
	`ie9ab_digicom_session`,
	`ie9ab_digicom_states`;