DROP TABLE IF EXISTS
	`#__digicom_cart`
	,`#__digicom_cartfields`
	,`#__digicom_categories`
	,`#__digicom_currencies`
	,`#__digicom_currency_symbols`
	,`#__digicom_customers`
	,`#__digicom_customfields`
	,`#__digicom_emailreminders`
	,`#__digicom_featuredproducts`
	,`#__digicom_field_types`
	,`#__digicom_fields`
	,`#__digicom_fieldsets`
	,`#__digicom_languages`
	,`#__digicom_licensefields`
	,`#__digicom_licenseprodfields`
	,`#__digicom_licenses`
	,`#__digicom_licenses_notes`
	,`#__digicom_licenses_payments`
	,`#__digicom_logs`
	,`#__digicom_mailtemplates`
	,`#__digicom_orders`
	,`#__digicom_plans`
	,`#__digicom_prodfields`
	,`#__digicom_product_categories`
	,`#__digicom_product_groups`
	,`#__digicom_product_groups_exp`
	,`#__digicom_productclass`
	,`#__digicom_products`
	,`#__digicom_products_emailreminders`
	,`#__digicom_products_images`
	,`#__digicom_products_plans`
	,`#__digicom_products_renewals`
	,`#__digicom_promocodes`
	,`#__digicom_promocodes_orders`
	,`#__digicom_promocodes_products`
	,`#__digicom_sendmails`
	,`#__digicom_session`
	,`#__digicom_settings`
	,`#__digicom_states`
	,`#__digicom_tax_customerclass`
	,`#__digicom_tax_productclass`
	,`#__digicom_tax_rate`
	,`#__digicom_tax_rule`
	,`#__digicom_taxplugin`
	,`#__digicom_topleveldomains`;